// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU4B7_jgcYoq1JVwPGzWE1vQyxrvC4vZ8',
    appId: '1:1028804800268:android:db70e82d1bba927c98e329',
    messagingSenderId: '1028804800268',
    projectId: 'e-customs-67c74',
    storageBucket: 'e-customs-67c74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPA-hi9QdDD_EwaWTanQ5ZiK7Yl4Sy2-U',
    appId: '1:1028804800268:ios:7b520ad96e753e1698e329',
    messagingSenderId: '1028804800268',
    projectId: 'e-customs-67c74',
    storageBucket: 'e-customs-67c74.firebasestorage.app',
    androidClientId: '1028804800268-15flp0lgkpu6a43i5eishjochgdkkmrd.apps.googleusercontent.com',
    iosClientId: '1028804800268-uoa2g4p9frviucoh830l3937h4jihft4.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickPdf',
  );
}
