// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:quick_pdf/features/scanner/data/models/group_model.dart';
import 'package:quick_pdf/features/scanner/data/models/image_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GroupModelAdapter());
    registerAdapter(ImageModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GroupModelAdapter());
    registerAdapter(ImageModelAdapter());
  }
}
